spring:
  application:
    name: spendev-authorization-ms
server:
  port: ${PORT:0}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance: ${spring.application.name}:${spring.application.instance_id:${random.value}}
